#!/bin/bash

SERVER_NAME=${ $1 :-server }

start() {
    docker run -d --name $SERVER_NAME -v $(pwd)/build:/www -v $(pwd)/default.conf:/etc/nginx/conf.d/default.conf nginx
}

stop() {
    docker rm -f $SERVER_NAME
}
